backend:
  name: github
  repo: ace718a/lease-rent
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "rent"
    label: "렌트 블로그"
    folder: "rent/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "발행일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
